### ISSUE TITLE
SA test datoteka v mapi Program

### ISSUE THREAD

**Issue by kokosinekm** [Marsovc1/Graffiti-conjecture-232#1]
Zanima me, ali je v vrstici "else: #razlika > rez" potrebno z neko verjetnostjo v slabši graf, ali lahko to izpustimo (nikoli ne izberemo tega grafa) in z verjetnostjo delamo le za grafe kjer "razlika == rez". Še vedno pa bi se ohranila konvergenca k globalnemu ekstremu?

**Comment by jaanos** [comment]
Tako je, tudi v primeru, ko dobita slabši graf, se vanj premakneta z določeno verjetnostjo. Pri metahevristiki [*simulated annealing*](https://en.wikipedia.org/wiki/Simulated_annealing#Pseudocode) ta verjetnost ni fiksna, pač pa je odvisna od t.i. temperature (vrednosti, ki pada tekom izvajanja algoritma) in poslabšanja ciljne funkcije (najlažje bo kar slediti predlaganim formulam s prejšnje povezave). Tako ne bo potrebno ločevati primera, ko dobita enakost.

Mimogrede, da ne bosta po nepotrebnem podvajala kode, svetujem, da si v vsakem koraku najprej naredita kopijo grafa
```sage
H = Graph(G)
```
in tega potem popravita. Če se algoritem odloči zanj, potem prepišeta `G` in trenutno razliko, sicer pa ga zavržeta (tako ne bo potrebno npr. povezav vračati v graf). Poleg tega hranita tudi trenutno najboljši graf in njegovo razliko - ni namreč nujno, da ga bo algoritem dosegel v zadnjem koraku.

**Comment by jaanos** [comment]
Mimogrede, še to sem opazil:
https://github.com/Marsovc1/Graffiti-conjecture-232/blob/7af822aeea038891a2493103a0249c2b0f754a34/Program/SA%20test.ipynb#L55
Tukaj preverita, ali se vozlišče `v2` ne pojavi kot krajišče (ali oznaka) povezave z indeksom `v1` v seznamu povezav - to seveda ni nujno povezava s krajiščem v `v1`. Sklepam, da želita preveriti, ali v grafu ni povezave med `v1` in `v2` - najučinkoviteje to naredita tako:
```sage
if not G.has_edge(v1, v2):
```

**Comment by kokosinekm** [comment]
Hvala za nasvete in popravke. Program sva popravila. Zanima naju, če je 'Acceptance probability' pravilno izračunana (else: p=...)?

**Comment by jaanos** [comment]
Verjetnost je pravilno izračunana, obrniti bo pa potrebno primerjavo z  `random()` - manjše kot je poslabšanje oziroma številka koraka, večja bo verjetnost, da se algoritem premakne v slabši graf.

Kot rečeno, hranita tudi najboljši do sedaj videni graf, saj ni nujno, da ga bosta dobila v zadnjem koraku.

**Comment by kokosinekm** [comment]
Hvala, spregledal sem, da je pri 'else:' rez-razlika <= 0. Dodala sva hranjenje najboljšega grafa in popravila primerjavo.
